flat_full.Rmd:
  path: dev/flat_full.Rmd
  state: active
  R:
  - R/my_median.R
  - R/my_other_median.R
  tests:
  - tests/testthat/test-my_median.R
  - tests/testthat/test-my_other_median.R
  vignettes: vignettes/get-started.Rmd
  inflate:
    flat_file: dev/flat_full.Rmd
    vignette_name: Get started
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
flat_tracking_inputs.Rmd:
  path: dev/flat_tracking_inputs.Rmd
  state: active
  R:
  - R/authenticate_google_drive.R
  - R/create_datapaths.R
  - R/has_drive_file_changed.R
  - R/mahery_input_files.R
  tests:
  - tests/testthat/test-authenticate_google_drive.R
  - tests/testthat/test-has_drive_file_changed.R
  - tests/testthat/test-create_datapaths.R
  vignettes: vignettes/tracking-input-data.Rmd
  inflate:
    flat_file: dev/flat_tracking_inputs.Rmd
    vignette_name: Tracking Input Data
    open_vignette: true
    check: true
    document: true
    overwrite: ask
    clean: ask
    codecov: false
